# My script for the Smart City Model Service. 
# Please feel free to adjust the syntax. This script is my test script!

# Initialize Model
initialize model smartcitymodel description "this is a smart city model" seed smartcity

# City Commands
# Define a city
# define city <city_id> name <name> account <address> lat <float> long <float> radius <float>

define city cambridge name Cambridge-MA account cambridge-account lat 42.3736 long -71.1097 radius 100
define city seattle name Seattle-WA account seattle-account lat 42.6062 long -122.3321 radius 100
define city tokyo name Tokyo-JPN account tokyo-account lat 35.6804 long 139.7690 radius 100
define city vancouver name Vancouver-BC account vancouver-account lat 49.2827 long 123.1207 radius 100

# Show the details of a city. Print out the details of the city including the id, name, account, location, people, and IoT devices.
# show city <city_id>

show city cambridge
show city seattle
show city tokyo
show city vancouver

# Device Commands
# Define a street sign
# define street-sign <city_id>:<device_id> lat <float> long <float> enabled (true|false) text <text>

define street-sign cambridge:ss_1 lat 42.3736 long -71.1097 enabled true text "Welcome to Cambridge!"
define street-sign seattle:ss_2 lat 42.6062 long -122.3321 enabled true text "Welcome to Seattle!"
define street-sign tokyo:ss_3 lat 35.6804 long 139.7690 enabled true text "Welcome to Tokyo!"
define street-sign vancouver:ss_4 lat 49.2827 long 123.1207 enabled true text "Welcome to Vancouver!"

# update a street sign
# update street-sign <city_id>:<device_id> [enabled (true|false)] [text <text>]

update street-sign seattle:ss_2 text "Seattle Seahawks vs. San Francisco 49ers!"

# Define an information kiosk
# define info-kiosk <city_id>:<device_id> lat <float> long <float> enabled (true|false) image <uri>

define info-kiosk cambridge:kiosk_1 lat 42.3723 long -71.1230 enabled true image https://media-cdn.tripadvisor.com/media/photo-s/05/94/cc/10/charles-hotel.jpg
define info-kiosk cambridge:kiosk_2 lat 42.3766 long -71.1160 enabled true image https://www.lwa-architects.com/wp-content/uploads/2014/12/Harvard-SciCtr_Ext-bikes-992x1250.jpg


# Update an information kiosk
# update info-kiosk <city_id>:<device_id> [enabled (true|false)] [image <uri>]

update info-kiosk cambridge:kiosk_1 enabled false
update info-kiosk cambridge:kiosk_2 image https://www.google.com/maps/place/Cambridge,+MA/@42.3737266,-71.1236297,16.23z/data=!4m5!3m4!1s0x89e370a5cb30cc5f:0xc53a8e6489686c87!8m2!3d42.3736158!4d-71.1097335


# Define a street light
# define street-light <city_id>:<device_id> lat <float> long <float> enabled (true|false) brightness <int>

define street-light cambridge:sl_1 lat 42.3770 long -71.1167 enabled true brightness 8
define street-light cambridge:sl_2 lat 42.3749 long -71.1218 enabled true brightness 5


# Update a street light
# update street-light <city_id>:<device_id> [enabled (true|false)] [brightness <int>]

update street-light cambridge:sl_1 brightness 4
update street-light cambridge:sl_1 enabled false brightness 5


# Define a parking space
# define parking-space <city_id>:<device_id> lat <float> long <float> enabled (true|false) rate <int>

define parking-space cambridge:ps_1 lat 42.3743 long -71.1202 enabled true rate 25
define parking-space cambridge:ps_2 lat 42.3744 long -71.1203 enabled true rate 25


# Update a parking space
# update parking-space <city_id>:<device_id> [enabled (true|false)] [rate <int>]

update parking-space cambridge:ps_1 rate 50
update parking-space cambridge:ps_2 rate 50


# Define a robot
# define robot <city_id>:<device_id> lat <float> long <float> enabled (true|false) activity <string>

define robot cambridge:bot_1 lat 42.3735 long -71.1205 enabled true activity "cleaning"
define robot cambridge:bot_2 lat 42.3729 long -71.1192 enabled true activity "assisting student"


# Update a robot
# update robot <city_id>:<device_id> [lat <float> long <float>] [enabled (true|false)] [activity <string>]

update robot cambridge:bot_1 lat 42.3732 long -71.1195
update robot cambridge:bot_2 activity "walking dog"


# Define a vehicle
# define vehicle <city_id>:<device_id> lat <float> long <float> enabled (true|false) type (bus|car) activity <string> capacity <int> fee <int>

define vehicle cambridge:car_1 lat 42.3725 long -71.1161 enabled true type car activity "parked" capacity 4 fee 10
define vehicle cambridge:bus_1 lat 42.3736 long -71.1214 enabled true type bus activity "on route" capacity 30 fee 1


# Update a vehicle
# update vehicle <city_id>:<device_id> [lat <float> long <float>] [enabled (true|false)] [activity <string>] [fee <int>]

update vehicle cambridge:car_1 lat 42.3830 long -71.1125 activity "driving"
update vehicle cambridge:bus_1 lat 42.3635 long -71.0985 enabled true activity "on route"


# Show the details of a device; if device id is omitted, show details for all devices within the city
# show device <city_id>[:<device_id>]

show device cambridge:bus_1
show device cambridge


# Simulate a device sensor event
# create sensor-event <city_id>[:<device_id>] type (microphone|camera|thermometer|co2meter) value <string> [subject <person_id>]

create sensor-event cambridge:bus_1 type microphone value "does this bus go to Central Square?" subject jane
create sensor-event cambridge:bus_1 type camera value "person boarding bus" subject jane
create sensor-event cambridge:sl_1 type thermometer value 80
create sensor-event cambridge:sl_1 type co2meter value 500
create sensor-event cambridge:bot_1 type thermometer value 98.6 joe

# Send a device output
# create sensor-output <city_id>[:<device_id>] type (speaker) value <string>

create sensor-output cambridge:bot_1 type speaker value "your temperature is normal"
create sensor-output cambridge type speaker value "severe weather alert, please take shelter"

# Person Commands
# Define a new Resident
# define resident <person_id> name <name> bio-metric <string> phone <phone_number> role (adult|child|administrator) lat <lat> long <long> account <account_address>

define resident resident_1 name jane bio-metric "voice-print='voiceprint-jane',face-print='faceprint-jane'" phone 781-222-3344 role adult lat 42.3735 long -71.1205 account janes_account


# Update a Resident
# update resident <person_id> [name <name>] [bio-metric <string>] [phone <phone_number>] [role (adult|child|administrator)] [lat <lat> long <long>] [account <account_address>]

update resident resident_1 name jane lat 42.3830 long -71.1125


# Define a new Visitor
# define visitor <person_id> bio-metric <string> lat <lat> long <long>

define visitor visitor_1 bio-metric "iris-print='irisprint-visitor_1'" lat 42.6062 long -122.3321


# Update a Visitor
# update visitor <person_id> [bio-metric <string>] [lat <lat> long <long>]

update visitor visitor_1 lat 42.3830 long -71.1125


# Show the details of the person
# show person <person_id>

show person resident_1
show person visitor_1

show city cambridge
show city seattle
show city tokyo
show city vancouver
